#!/usr/bin/env python3
"""Turn a script into timestamped segments for a Remotion edit.

Two modes:

1. SRT/VTT mode (preferred — use whenever you have one): if the voiceover
   was generated by a TTS tool or transcribed with word/line timestamps,
   pass that .srt file. Timestamps come straight from it, which reflects
   real speech pacing (pauses, emphasis) far better than a word-count
   guess ever could.

       python3 segment_script.py --srt voiceover.srt --fps 30

2. Plain-text mode (fallback — use only when no timed transcript exists):
   pass the script text plus the voiceover's total duration in seconds.
   Time is allocated to each line proportional to its word count. This is
   an approximation: real narration doesn't move at a constant words/sec
   rate, so treat the output as a first draft and nudge boundaries by ear
   once the voiceover is laid into Remotion — don't trust it blindly.

       python3 segment_script.py --text script.txt --duration 42.5 --fps 30

Either mode prints a JSON array to stdout:
  [{"index": 0, "start_frame": 0, "end_frame": 88, "start_s": 0.0,
    "end_s": 2.93, "text": "..."}, ...]
"""
import argparse
import json
import re
import sys


def parse_srt_timestamp(ts: str) -> float:
    # 00:00:01,240 -> seconds
    h, m, rest = ts.split(":")
    s, ms = rest.split(",")
    return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000


def parse_srt(path: str):
    with open(path, encoding="utf-8") as f:
        content = f.read()
    blocks = re.split(r"\n\s*\n", content.strip())
    segments = []
    for block in blocks:
        lines = [l for l in block.splitlines() if l.strip()]
        if len(lines) < 2:
            continue
        # lines[0] is the cue number, lines[1] is the timing line
        timing_line_idx = 1 if re.match(r"^\d+$", lines[0].strip()) else 0
        timing_match = re.match(
            r"(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})",
            lines[timing_line_idx],
        )
        if not timing_match:
            continue
        start_s = parse_srt_timestamp(timing_match.group(1))
        end_s = parse_srt_timestamp(timing_match.group(2))
        text = " ".join(lines[timing_line_idx + 1 :]).strip()
        if text:
            segments.append((start_s, end_s, text))
    return segments


def parse_plain_text(path: str, total_duration: float):
    with open(path, encoding="utf-8") as f:
        content = f.read()
    # One segment per non-empty line. Encourage the caller to pre-split the
    # script into the beats they want cut on — that's a creative decision,
    # not something to infer automatically from punctuation.
    lines = [l.strip() for l in content.splitlines() if l.strip()]
    if not lines:
        raise ValueError("script text has no non-empty lines")

    word_counts = [max(len(l.split()), 1) for l in lines]
    total_words = sum(word_counts)

    segments = []
    cursor = 0.0
    for line, words in zip(lines, word_counts):
        share = words / total_words
        duration = total_duration * share
        segments.append((cursor, cursor + duration, line))
        cursor += duration
    # Snap the last segment's end to the exact total to avoid float drift.
    if segments:
        start, _, text = segments[-1]
        segments[-1] = (start, total_duration, text)
    return segments


def to_frame_json(segments, fps: float):
    out = []
    for i, (start_s, end_s, text) in enumerate(segments):
        out.append(
            {
                "index": i,
                "start_s": round(start_s, 3),
                "end_s": round(end_s, 3),
                "start_frame": round(start_s * fps),
                "end_frame": round(end_s * fps),
                "text": text,
            }
        )
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--srt", help="Path to a timed .srt/.vtt-style transcript")
    parser.add_argument("--text", help="Path to a plain-text script (one beat per line)")
    parser.add_argument("--duration", type=float, help="Total voiceover duration in seconds (plain-text mode)")
    parser.add_argument("--fps", type=float, default=30, help="Composition fps (default 30)")
    args = parser.parse_args()

    if args.srt:
        segments = parse_srt(args.srt)
    elif args.text:
        if not args.duration:
            print("error: --duration is required with --text", file=sys.stderr)
            sys.exit(1)
        segments = parse_plain_text(args.text, args.duration)
    else:
        print("error: pass either --srt or --text", file=sys.stderr)
        sys.exit(1)

    print(json.dumps(to_frame_json(segments, args.fps), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
